name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-analyze:
    name: Flutter Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Install dependencies
        run: flutter pub get
        working-directory: Frontend

      - name: Analyze Flutter
        run: flutter analyze
        working-directory: Frontend

      - name: Run Flutter tests
        run: flutter test
        working-directory: Frontend

  nest-analyze:
    name: NestJS Quality
    runs-on: ubuntu-latest
    needs: flutter-analyze

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: Backend

      - name: Lint NestJS
        run: npm run lint
        working-directory: Backend
      - name: Run backend tests
        run: npm run test
        working-directory: Backend